(function(){
'use strict';
const KEY='decisionbrief:v1';
const uid=()=>Math.random().toString(36).slice(2,9);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({question:'',deadline:'',nextAction:'',unknowns:'',mind:'',options:[{id:uid(),name:'',note:'',url:'',scores:{}},{id:uid(),name:'',note:'',url:'',scores:{}}],criteria:[{id:uid(),name:'',weight:3},{id:uid(),name:'',weight:3},{id:uid(),name:'',weight:3}]});
const sample=()=>({version:1,question:'Which project-management tool should our small team try?',deadline:'2026-10-01',nextAction:'Invite the team to a one-week trial and check export quality.',unknowns:'Will the team keep using it after the trial? Does the free plan cover our needs?',mind:'A poor export, hidden cost, or low adoption after one week.',options:[{id:uid(),name:'Tool A',note:'Familiar interface and good mobile app.',url:'https://example.com/tool-a',scores:{}},{id:uid(),name:'Tool B',note:'Flexible views, but more setup.',url:'https://example.com/tool-b',scores:{}},{id:uid(),name:'Tool C',note:'Simple and affordable, fewer integrations.',url:'https://example.com/tool-c',scores:{}}],criteria:[{id:uid(),name:'Ease of adoption',weight:4},{id:uid(),name:'Fits our workflow',weight:5},{id:uid(),name:'Cost to start',weight:2},{id:uid(),name:'Data portability',weight:3}]});
const textField=(value,max)=>typeof value==='string'&&value.length<=max;
function normalize(input){
  if(!input||typeof input!=='object'||Array.isArray(input)||input.version!==1)return null;
  const rootFields={question:180,deadline:40,nextAction:160,unknowns:1600,mind:1600};
  if(!Object.keys(rootFields).every(k=>textField(input[k],rootFields[k])))return null;
  if(!Array.isArray(input.options)||input.options.length<2||input.options.length>8||!Array.isArray(input.criteria)||input.criteria.length<3||input.criteria.length>6)return null;
  const ids=new Set();
  const criteria=input.criteria.map(c=>{
    if(!c||typeof c!=='object'||Array.isArray(c)||typeof c.id!=='string'||!c.id||ids.has(c.id)||!textField(c.id,80)||!textField(c.name,80)||!Number.isInteger(c.weight)||c.weight<1||c.weight>5)return null;
    ids.add(c.id);return {id:c.id,name:c.name,weight:c.weight};
  });
  if(criteria.some(c=>!c))return null;
  const optionIds=new Set();
  const options=input.options.map(o=>{
    if(!o||typeof o!=='object'||Array.isArray(o)||typeof o.id!=='string'||!o.id||optionIds.has(o.id)||!textField(o.id,80)||!textField(o.name,100)||!textField(o.note,500)||!textField(o.url,2048)||!o.scores||typeof o.scores!=='object'||Array.isArray(o.scores))return null;
    optionIds.add(o.id);
    const scores={};
    for(const key of Object.keys(o.scores)){
      if(!ids.has(key))return null;
      const value=o.scores[key];
      if(value!==null&&(!Number.isInteger(value)||value<1||value>5))return null;
      if(value!==null)scores[key]=value;
    }
    return {id:o.id,name:o.name,note:o.note,url:o.url,scores};
  });
  if(options.some(o=>!o))return null;
  return {version:1,question:input.question,deadline:input.deadline,nextAction:input.nextAction,unknowns:input.unknowns,mind:input.mind,options,criteria};
}
function scoreOptions(options,criteria){return options.map(o=>{let total=0,possible=0,scored=0;criteria.forEach(c=>{const v=o.scores?.[c.id];if(Number.isInteger(v)&&v>=1&&v<=5){total+=v*c.weight;possible+=5*c.weight;scored++}});return {...o,total,possible,scored,coverage:criteria.length?Math.round(scored/criteria.length*100):0,pct:possible?Math.round(total/possible*100):0};}).sort((a,b)=>b.pct-a.pct||b.scored-a.scored||a.name.localeCompare(b.name));}
if(typeof window!=='undefined')window.DecisionBrief={normalize,scoreOptions};
let state=normalize({...blank(),version:1})||blank();
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)))||blank();}catch(_){return blank();}}
state=load();
function save(msg){localStorage.setItem(KEY,JSON.stringify(state));renderResults();if(msg)status(msg)}
function status(m){document.querySelector('#status').textContent=m;clearTimeout(status.t);status.t=setTimeout(()=>document.querySelector('#status').textContent='',3000)}
function render(){document.querySelector('#question').value=state.question;document.querySelector('#deadline').value=state.deadline;document.querySelector('#nextAction').value=state.nextAction;document.querySelector('#unknowns').value=state.unknowns;document.querySelector('#mind').value=state.mind;renderOptions();renderCriteria();renderResults()}
function renderOptions(){const el=document.querySelector('#options');el.innerHTML=state.options.map((o,i)=>`<article class="repeat-item"><div class="repeat-top"><div><label for="on-${o.id}">Option ${i+1}</label><input id="on-${o.id}" data-option="${o.id}" data-field="name" maxlength="100" value="${esc(o.name)}" placeholder="Name this option"></div><button type="button" class="remove" data-remove-option="${o.id}" ${state.options.length<=2?'disabled':''}>Remove</button></div><div class="repeat-meta"><div><label for="note-${o.id}">Evidence or note</label><textarea id="note-${o.id}" data-option="${o.id}" data-field="note" rows="2" maxlength="500" placeholder="What do you know so far?">${esc(o.note)}</textarea></div><div><label for="url-${o.id}">Source URL <span class="muted">(optional)</span></label><input id="url-${o.id}" data-option="${o.id}" data-field="url" type="url" value="${esc(o.url)}" placeholder="https://..."></div></div><div class="option-score-grid">${state.criteria.map(c=>`<div class="score-cell"><label for="sc-${o.id}-${c.id}">${esc(c.name||'Unnamed criterion')}</label><select id="sc-${o.id}-${c.id}" data-score-option="${o.id}" data-score-criterion="${c.id}"><option value="">Not scored</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${Number(o.scores?.[c.id])===n?'selected':''}>${n} / 5</option>`).join('')}</select></div>`).join('')}</div></article>`).join('')}
function renderCriteria(){const el=document.querySelector('#criteria');el.innerHTML=state.criteria.map((c,i)=>`<article class="repeat-item"><div class="repeat-top"><div><label for="cn-${c.id}">Criterion ${i+1}</label><input id="cn-${c.id}" data-criterion="${c.id}" data-field="name" maxlength="80" value="${esc(c.name)}" placeholder="What matters?"></div><div style="max-width:150px"><label for="cw-${c.id}">Weight</label><select id="cw-${c.id}" data-criterion="${c.id}" data-field="weight">${[1,2,3,4,5].map(n=>`<option value="${n}" ${Number(c.weight)===n?'selected':''}>${n}</option>`).join('')}</select></div><button type="button" class="remove" data-remove-criterion="${c.id}" ${state.criteria.length<=3?'disabled':''}>Remove</button></div></article>`).join('')}
function renderResults(){const el=document.querySelector('#results');if(state.options.length<2||state.criteria.length<3){el.innerHTML='<div class="empty">Add at least 2 options and 3 criteria to see a result.</div>';return}const ranked=scoreOptions(state.options,state.criteria),leader=ranked[0],hasNames=leader&&leader.name;if(!hasNames){el.innerHTML='<div class="empty">Name your options and criteria to see the trade-offs.</div>';return}const max=Math.max(...ranked.map(x=>x.pct),1);el.innerHTML=`<div class="result-summary"><div class="leader"><small>Current entered leader</small><strong>${esc(leader.name||'Unnamed')}</strong><p>${leader.scored?leader.pct+'% score among scored criteria':''}${leader.scored?' with '+leader.coverage+'% criteria coverage.':'No criteria scored yet.'}</p></div><div class="rank-list">${ranked.map((x,i)=>`<div class="rank-row"><span class="rank-number">${i+1}</span><div><strong>${esc(x.name||'Unnamed')}</strong><div class="bar" aria-label="${x.pct}% score among ${x.scored} scored criteria, ${x.coverage}% coverage"><span style="width:${Math.round(x.pct/max*100)}%"></span></div></div><span class="rank-score">${x.scored?x.pct+'%':'No score'} <small>(${x.coverage}% covered)</small></span></div>`).join('')}</div></div><p class="result-note"><strong>Read this carefully:</strong> scores compare only entered criteria. Missing scores are incomplete evidence, not a quality deficit; review coverage and unknowns before acting.</p>`}
function markdown(){const ranked=scoreOptions(state.options,state.criteria);return `# ${state.question||'Decision brief'}\n\n${state.deadline?'**Deadline:** '+state.deadline+'\n':''}${state.nextAction?'**Next action:** '+state.nextAction+'\n':''}\n> This brief organizes user-entered inputs. It is not professional advice or objective truth.\n\n## Current entered result\n\n${ranked.map((o,i)=>`${i+1}. **${o.name||'Unnamed option'}** - ${o.scored?o.pct+'% among scored criteria':'No score'} (${o.scored}/${state.criteria.length} criteria scored; ${o.coverage}% coverage)`).join('\n')}\n\n## Criteria and scores\n\n| Option | ${state.criteria.map(c=>c.name||'Unnamed').join(' | ')} |\n|---|${state.criteria.map(()=>':---:').join('|')}|\n${state.options.map(o=>`| ${o.name||'Unnamed'} | ${state.criteria.map(c=>o.scores?.[c.id]||'not scored').join(' | ')} |`).join('\n')}\n\n## Evidence\n\n${state.options.map(o=>`### ${o.name||'Unnamed'}\n${o.note||'No note added.'}${o.url?'\n\nSource: '+o.url:''}`).join('\n\n')}\n\n## Unknowns\n\n${state.unknowns||'Not recorded.'}\n\n## What would change my mind\n\n${state.mind||'Not recorded.'}\n`}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function jsonExport(){download('decision-brief.json',JSON.stringify({version:1,...state},null,2),'application/json');status('JSON backup downloaded.')}
function bind(){document.addEventListener('input',e=>{const t=e.target;if(t.dataset.option){const o=state.options.find(x=>x.id===t.dataset.option);if(o)o[t.dataset.field]=t.value}if(t.dataset.criterion){const c=state.criteria.find(x=>x.id===t.dataset.criterion);if(c)c[t.dataset.field]=t.value}if(['question','deadline','nextAction','unknowns','mind'].includes(t.id))state[t.id]=t.value;save()});document.addEventListener('change',e=>{const t=e.target;if(t.dataset.scoreOption){const o=state.options.find(x=>x.id===t.dataset.scoreOption);o.scores[t.dataset.scoreCriterion]=t.value?Number(t.value):null}if(t.dataset.criterion&&t.dataset.field==='weight'){state.criteria.find(x=>x.id===t.dataset.criterion).weight=Number(t.value)}save()});document.addEventListener('click',e=>{const t=e.target;if(t.dataset.removeOption){state.options=state.options.filter(x=>x.id!==t.dataset.removeOption);save('Option removed.');renderOptions()}if(t.dataset.removeCriterion){const id=t.dataset.removeCriterion;state.criteria=state.criteria.filter(x=>x.id!==id);state.options.forEach(o=>delete o.scores[id]);save('Criterion removed.');renderCriteria();renderOptions()}if(t.id==='addOption'&&state.options.length<8){state.options.push({id:uid(),name:'',note:'',url:'',scores:{}});renderOptions();status('Option added.')}if(t.id==='addCriterion'&&state.criteria.length<6){state.criteria.push({id:uid(),name:'',weight:3});renderCriteria();renderOptions();status('Criterion added.')}if(t.id==='sampleBtn'){state=sample();save('Starter template loaded.');render()}if(t.id==='exportBtn'||t.id==='jsonBtn')jsonExport();if(t.id==='markdownBtn'){download('decision-brief.md',markdown(),'text/markdown');status('Markdown brief downloaded.')}if(t.id==='printBtn'){window.print()}});document.querySelector('#importBtn').onclick=()=>document.querySelector('#fileInput').click();document.querySelector('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>500000){status('Import refused: file is too large.');return}const r=new FileReader();r.onload=()=>{try{const imported=normalize(JSON.parse(r.result));if(!imported)throw Error();state=imported;save('Import complete.');render()}catch(_){status('Import refused: invalid Decision Brief JSON. Your current brief is unchanged.')}};r.readAsText(f)}}
bind();render();
})();
